version: '3.7'

services:

  pomerium:
    image: pomerium/pomerium:latest
    volumes:
      - ./config/pomerium.yml:/pomerium/config.yaml:ro
      - ./config/pomerium.crt:/pomerium/cert.pem:ro
      - ./config/pomerium.key:/pomerium/certprivkey.pem:ro
    ports:
      - 8080:443
    environment:
      - CERTIFICATE_FILE=/pomerium/cert.pem
      - CERTIFICATE_KEY_FILE=/pomerium/certprivkey.pem
      - POMERIUM_DEBUG=true
      - AUTHENTICATE_SERVICE_URL=https://localhost:8080
      - GRPC_INSECURE=TRUE
      - COOKIE_SECRET=V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI=
      - IDP_PROVIDER=google
      - IDP_PROVIDER_URL=https://accounts.google.com
      - IDP_CLIENT_ID=${IDP_CLIENT_ID}
      - IDP_CLIENT_SECRET=${IDP_CLIENT_SECRET}
      - IDP_SERVICE_ACCOUNT=${IDP_SERVICE_ACCOUNT}
    networks:
      - elk

  kibana:
    image: kibana:7.6.1
    networks:
      - elk
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: elasticsearch:7.6.1
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: password
      discovery.type: single-node

  logstash:
    image: logstash:7.6.1
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

networks:
  elk:
    driver: bridge
