version: '3.7'

services:

  kibana:
    image: kibana:7.6.1
    networks:
      - elk
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: elasticsearch:7.6.1
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: password
      discovery.type: single-node

  logstash:
    image: logstash:7.6.1
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

networks:
  elk:
    driver: bridge
